basePath: /v1
consumes:
    - application/json
definitions:
    User:
        properties:
            id:
                type: number
                format: double
            name:
                type: string
        required:
            - id
            - name
        type: object
info:
    title: typescript-nodejs-starter-kit
    version: 0.1.0
    license:
        name: Apache-2.0
paths:
    /users:
        get:
            operationId: GetUsers
            produces:
                - application/json
            responses:
                '200':
                    description: Ok
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/User'
            security: []
            parameters: []
produces:
    - application/json
swagger: '2.0'
securityDefinitions: {}
host: 'localhost:3000'
